export const DECKS_STORAGE_KEY = 'Mobile-cards:decks'
export const QUESTION_PLACEHOLDER = 'Question'
export const ANSWER_PLACEHOLDER = 'Answer'
export const DECK_PLACEHOLDER = 'Deck Title'
export const CORRECT_ANSWER = 'CORRECT_ANSWER'
export const INCORRECT_ANSWER = 'INCORRECT_ANSWER'
