export const DECKS_STORAGE_KEY = 'Mobile-cards:decks'
export const QUESTION_PLACEHOLDER = 'Question'
export const ANSWER_PLACEHOLDER = 'Answer'
export const DECK_PLACEHOLDER = 'Deck Title'
export const YES_ANSWER = 'Yes'
export const NO_ANSWER = 'No'
